### ISSUE TITLE
The icon offsets on the Abilities tab is broken in v0.8.2

### ISSUE THREAD

**Issue by intopuddles** [Lyall/FFXVIFix#71] opened 2024-09-24 04:33 UTC
Upon applying v0.8.2, moving the cursor to any of the ability icons on the Abilities tab will not show the typical context menu to Learn/Reset/Upgrade. Upon moving the cursor somewhere off to the left of the icons, I can get the context menus to appear. Removing the fix, or simply downgrading the v0.8.1 make it work as normal.

**Comment by Lyall** [comment] 2024-09-24 08:20
Are you able to show a screenshot of the issue? Also does it happen after a cutscene? Like in #64, I can't seem to replicate the issue. Agh, this movie fix'll be the death of me 😭 .

**Comment by intopuddles** [comment] 2024-09-24 09:07
Notice the cursor position. The proper icon for that tooltip is peaking offscreen in the top-center-right.

![cursor](https://i.imgur.com/8SGwiv8.png)

Two things to note. It actually fixed itself _once_ when I initially turned off HDR for the screenshot. I restarted to see if I was able to replicate that, but it went back to broken. Also, not fully related, but I got the "Operated Completed" crash again when alt+tabbing back into the game while in fullscreen, which crashes the game and often locks up PC.

**Comment by Lyall** [comment] 2024-09-24 09:18
Hmm maybe it's not related to 8ba9c20. Can you see if you can replicate the issue with "Fix Movies" set to disabled in `FFXVIFix.ini`? If that doesn't fix it, can you then try with all the options under `[Game Window]` set to false?

**Comment by intopuddles** [comment] 2024-09-24 10:10
So I played around with it a bit. Applied the fix, booted up game in Borderless, and the issue is gone. Switched to Fullscreen, still no issue. Restarted game into Fullscreen, now the issue happens. Switched to Borderless, still an issue. Went back to Fullscreen but with no HDR, and restarted, issue is gone again. Then I restarted with Fullscreen+HDR enabled and tried Fix Movies=False, still an issue. Then I restarted with Fullscreen+HDR enabled with Fix Movies still false and all Game Window on false, with no issue this time. Then I kept all previous changes and just enabled DisableScreensaver, and had the issue. Then I disabled HDR and it went away. Enabled HDR again, restarted, and it issue is there again. Changed to Borderless and restarted, the issue is there still. 

Yah I don't know. Just going back to v0.8.1 for now lol

**Comment by Lyall** [comment] 2024-09-24 15:41
That's some classic troubleshooting madness there, bugs that don't happen consistently can be infuriating. I saw a comment on the Nexus Mods page suggesting that setting "LockCursor" to false fixes it. That would make sense if it's not relating to the movie fix update from before.

**Comment by Eve-Knight** [comment] 2024-09-24 17:36
Setting "LockCursor" to false does not fix this for me.

**Comment by shauns2007** [comment] 2024-09-24 18:28
![image](https://github.com/user-attachments/assets/b18edb0e-d345-40a9-8fbe-eb7dd5136311)

I have to move the ability I want to select to underneath the Abilities word for it to work.

**Comment by jacklul** [comment] 2024-09-24 21:17
The same happens with fast travel buttons, randomly you can't fast travel until you restart your game.
Can't hover over fast travel points at all.

**Comment by Lyall** [comment] 2024-09-24 21:27
Okay, since I haven't been able to replicate it, I'll need some of you that are affected by the issue to do some testing with me. This is a build with the window management stuff forced off, just to rule that out completely.

[FFXVIFix_v0.8.3_test.zip](https://github.com/user-attachments/files/17121286/FFXVIFix_v0.8.3_test.zip)

**Comment by VagrantZero** [comment] 2024-09-24 21:28
> Okay, since I haven't been able to replicate it, I'll need some of you that are affected by the issue to do some testing with me. This is a build with the window management stuff forced off, just to rule that out completely.
> 
> [FFXVIFix_v0.8.3_test.zip](https://github.com/user-attachments/files/17121286/FFXVIFix_v0.8.3_test.zip)

Do you play with a controller? I was using my mouse for a quick moment and ran into the problem jacklul described, but the second I switched to my xbox controller I was able to fast travel again.

**Comment by Lyall** [comment] 2024-09-24 21:29
> Do you play with a controller? I was using my mouse for a quick moment and ran into the problem jacklul described, but the second I switched to my xbox controller I was able to fast travel again.

I go back and forth, using a controller when I'm actually playing and M+K when I'm testing/working on the fix.

**Comment by Eve-Knight** [comment] 2024-09-25 05:40
The problem is totally consistent for me. I use three screens, each 3440 x 1440. Always mouse and keyboard. Testing fix ...

Success! <victory theme music plays>

**Comment by Lyall** [comment] 2024-09-25 08:58
> The problem is totally consistent for me. I use three screens, each 3440 x 1440. Always mouse and keyboard. Testing fix ...
> 
> Success!
> 
> ... although now background audio is broken (it mutes when out of focus) ... and lock cursor is broken (I have to use full screen to lock the cursor).

This is with the build "FFXVIFix_v0.8.3_test.zip" from my previous post right? That build has all the window management stuff disabled just to try and narrow down the issue.

If that build worked for you, can you try this new build?

[FFXVIFix_v0.8.3_test2.zip](https://github.com/user-attachments/files/17128218/FFXVIFix_v0.8.3_test2.zip)

**Comment by Eve-Knight** [comment] 2024-09-25 09:03
It is, yes.

Sure ... testing ...

This re-introduces the primary problem of the tooltips not appearing for obelisks and abilities.

**Comment by Lyall** [comment] 2024-09-25 09:45
Okay so the problem is definitely isolated to the window management code. Narrowing it down helps at least. I'll reach out to Kaldaien and see if there are any theories as to what the issue is.

**Comment by truduEprocEss** [comment] 2024-09-25 09:54
This just happened to me today, though it wasn't an issue yesterday. But you know what fixed it for the session? Tabbing out and tabbing back into the game. Very strange indeed.

**Comment by Lyall** [comment] 2024-09-25 10:38
> It is, yes.
> 
> Sure ... testing ...
> 
> This re-introduces the primary problem of the tooltips not appearing for obelisks and abilities.

Can you try this test build? It includes the latest changes from #77.

[FFXVIFix_v0.8.3_test3.zip](https://github.com/user-attachments/files/17129448/FFXVIFix_v0.8.3_test3.zip)

**Comment by Eve-Knight** [comment] 2024-09-25 10:44
Sure ...

Looks good. Have ability tooltips, locked cursor, and unfocused audio.

**Comment by Kaldaien** [comment] 2024-09-25 13:33
This is my bad, sorry.
The window frame wasn't updating until you click the game's title bar.
Special K automatically fixes the problem, so I missed it until I did testing without it :)

**Comment by Lyall** [comment] 2024-09-25 17:34
This should be fixed now in v0.8.3

**Closed by Lyall** 2024-09-25 17:34 UTC
