### ISSUE TITLE
World Map Descriptions Newly Broken in 0.8.2

### ISSUE THREAD

**Issue by Eve-Knight** [Lyall/FFXVIFix#72] opened 2024-09-24 05:47 UTC
When I hover over a location, its description no longer displays with 0.8.2. The description for my present location displays once, but it sticks even when I stop pointing to that location. And then when I point to a different destination, it disappears but is not replaced with the description for the new location. And even if I point back to the original location, no description displays. Reverting to 0.8.1 restores the functionality.

**Comment by Lyall** [comment] 2024-09-24 17:27
Dupe of #71. Try setting "LockCursor" to false in `FFXVIFix.ini`.

**Closed by Lyall** 2024-09-24 17:27 UTC
