### ISSUE TITLE
.82 Map Issue

### ISSUE THREAD

**Issue by nathanbarling** [Lyall/FFXVIFix#76] opened 2024-09-25 04:21 UTC
I am unable to engage on the world map to quick teleport to a location. It chooses 'The hideaway' every single time I attempt to port to any location on the map even though I have my mouse over a different location. When I install version 0.81 to world map has no issues teleporting. I have attempted a clean removal and installation of .82 but the issue remains.

I am playing on PC through Steam on 3440 x 1440 ultra-widescreen on a RTX 4090 with HDR enabled using the FFXIVFix.ini that was included in the .82 repo download.

**Comment by Lyall** [comment] 2024-09-25 13:41
Dupe of #72.

**Closed by Lyall** 2024-09-25 13:41 UTC
