### ISSUE TITLE
Map shifting after cutscenes.

### ISSUE THREAD

**Issue by hawk16zz** [Lyall/FFXVIFix#64] opened 2024-09-22 20:59 UTC
I have had this happen twice since upgrading from 0.7.9 to 0.8.1 I suspect it may be related to the cutscene letter/pillarbox fix as the first time it happened after a series of cutscenes and the second after one from Vivian.
[FFXVIFix.log](https://github.com/user-attachments/files/17091257/FFXVIFix.log)
![2515020_20240922161852_1](https://github.com/user-attachments/assets/ba8bb5ce-dee5-4034-8d11-b7ed91e65368)

Edit: I upgraded back to 0.8.1 to record a video of it happening https://youtu.be/QbTlSMT7cf4 I can also confirm it didn't happen on 0.8.0 when downgrading to it

**Comment by Lyall** [comment] 2024-09-22 22:44
Yeah it's almost certainly related to the cutscene fix from the latest update. Does the map fix itself if you open/close it? Or does it remain cut off like in the picture?

**Comment by hawk16zz** [comment] 2024-09-22 22:48
Stays shifted over like that until I restart the game. I am unsure though if going to the main menu fixes it.

**Comment by Lyall** [comment] 2024-09-22 22:54
Do you have a save file of that spot you could share? Would be handy for testing. 

The saves should be in `C:\Users\~USER\Documents\My Games\FINAL FANTASY XVI\Steam\~STEAMID\`. They're PNGs funnily enough but you probably want to zip them in case uploading to GitHub strips anything from the image metadata.

**Comment by hawk16zz** [comment] 2024-09-22 22:58
> They're PNGs funnily enough
That's hilarious! And sure, no problem!
[0004.zip](https://github.com/user-attachments/files/17091541/0004.zip)

**Comment by Lyall** [comment] 2024-09-22 23:40
> > They're PNGs funnily enough
> 
> That's hilarious! And sure, no problem! [0004.zip](https://github.com/user-attachments/files/17091541/0004.zip)

Thanks for uploading that. Loaded it and got a ton of achievements! I can't seem to replicate the bug though. Here's what happens on my end:
https://i.imgur.com/aqTbRPO.mp4

Can you post your `FFXVIFix.log` file? It looks like in the video you have a spanned HUD so I'll see if I can match your settings.

**Comment by hawk16zz** [comment] 2024-09-23 00:07
Interesting. I have a log attached in the first post from when I was running 0.8.1. Other information that might be relevant is I have 3 monitors, one to each side of my ultrawide. While the one on the right matches height at 1080p the one to the left is an old tv I have set to 1360x765 since I just put yt on it to fall asleep to.

**Comment by Lyall** [comment] 2024-09-23 00:13
> Interesting. I have a log attached in the first post from when I was running 0.8.1. Other information that might be relevant is I have 3 monitors, one to each side of my ultrawide. While the one on the right matches height at 1080p the one to the left is an old tv I have set to 1360x765 since I just put yt on it to fall asleep to.

Dunno how I missed your log (I may be going blind). I'll match your settings and see if I can replicate the bug.

**Comment by Lyall** [comment] 2024-09-23 00:19
Alright here's with settings as closely matched to yours as I can get them.

https://i.imgur.com/yr08rsp.mp4

Still no bug on my end. Is it easily reproducible for you if you pop in to the save again?

**Comment by hawk16zz** [comment] 2024-09-23 00:43
Yep, happens every time on 0.8.1 so far. I've tried setting the hud back to '3' 16:9, "moving" my tv to the otherside, setting my res to 2560x1080 in the ini, turning fram gen off. It just keeps shifting. I'm gonna try restarting my computer but wanted to jot all that down before I forgot.

**Comment by Lyall** [comment] 2024-09-23 01:04
Hmm, I wish I could replicate the bug on my end. Are you using DLSS (w/frame gen?) or FSR? Also, could you try all the options in the `[Game Window]` section of `FFXVIFix.ini` set to false? That should skip over the window management stuff which is one of the bigger changes between v0.7.9 and v0.8.1.

**Comment by hawk16zz** [comment] 2024-09-23 01:17
FSR3 w/ frame gen since I'm on a 3060, I set the screensaver to false as that was the only one set to 'true:' still doing it. I'll try turning off FSR since I just disabled the framegen part last time: THAT DID IT. So there's some interaction with the changes from 0.8.0 to 0.8.1 and FSR3.

**Comment by hawk16zz** [comment] 2024-09-23 01:31
Oh, there's something more to it though while the map stayed in the right spot all the icons are still shifted

**Comment by Jipper88** [comment] 2024-09-23 11:15
Hi, 

I can confirm i also have this same issue, Icons bumping the cursor away so making fast travel impossible. 

I dont use any framegen, but do use DLSS.

attached my .log 

![image](https://github.com/user-attachments/assets/165eed9c-662a-4387-8480-7da1cd413dc1)
[FFXVIFix.log](https://github.com/user-attachments/files/17096575/FFXVIFix.log)

**Comment by Jipper88** [comment] 2024-09-23 14:30
Yeah thats the same for me, if i use the mouse it works but using controller its impossible. hopefully its a quick fix, or can just go back to 8.0 for now

**Comment by Lyall** [comment] 2024-09-23 15:21
> FSR3 w/ frame gen since I'm on a 3060, I set the screensaver to false as that was the only one set to 'true:' still doing it. I'll try turning off FSR since I just disabled the framegen part last time: THAT DID IT. So there's some interaction with the changes from 0.8.0 to 0.8.1 and FSR3.

So, I've just tried with FSR3 Quality and frame generation on, I even used a controller and I still can't replicate this issue. 

https://i.imgur.com/p02UshY.mp4

I'm a bit mystified by this, being unable to replicate the issue makes it very hard to fix. I'll have a closer look at my code for resizing the movies, perhaps there are additional checks I can put in place.

**Comment by Jipper88** [comment] 2024-09-23 15:34
Yeah, so I've put false for movie resizing and now no longer have the issue with the black bars at the side in the map screen and the icons aren't bumping the cursor.

**Comment by hawk16zz** [comment] 2024-09-23 15:48
Can confirm setting [Fix Movies] to 'false' fixes the map! That's the one thing I didn't check before. Would it be possible to make a toggle separate for the portion that fixed the background showing through?

I also wanted to say you're doing a bang up job with all of your fix mods, I've been using them for a while even since I found the one for LAD: Isshin and I always check your repos first when I start a new game without proper ultrawide support!

**Comment by Lyall** [comment] 2024-09-23 16:03
> Can confirm setting [Fix Movies] to 'false' fixes the map! That's the one thing I didn't check before. Would it be possible to make a toggle separate for the portion that fixed the background showing through?

It's not unfortunately, I would have stuck with the other method of fixing the movies had that been an option. The problem is that I'm resizing an entire UI layer essentially as a movie starts and then quickly resizing it back when the movie ends. It's probably just a matter of finding exactly the right place to do it.

> I also wanted to say you're doing a bang up job with all of your fix mods, I've been using them for a while even since I found the one for LAD: Isshin and I always check your repos first when I start a new game without proper ultrawide support!

Thanks!

**Comment by hawk16zz** [comment] 2024-09-23 16:35
> It's not unfortunately, I would have stuck with the other method of fixing the movies had that been an option. The problem is that I'm resizing an entire UI layer essentially as a movie starts and then quickly resizing it back when the movie ends. It's probably just a matter of finding exactly the right place to do it.

Gotcha! If you need a guinea pig to test a build I'm more than willing, lol!

**Comment by Lyall** [comment] 2024-09-23 16:42
I do have a test build you could try. It reworks the movie fix a bit to not write to memory addresses instead.

[FFXVIFix_v0.8.2_test.zip](https://github.com/user-attachments/files/17101021/FFXVIFix_v0.8.2_test.zip)

**Comment by hawk16zz** [comment] 2024-09-23 16:58
From an initial test... IT WORKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
![2515020_20240923125002_1](https://github.com/user-attachments/assets/b33e2dd9-c178-4764-9e39-ee88d53111b0) Map's staying put, markers aren't shifting, cursor snapping with the controller is working normally. I think you've done it!!! A god among modders! Can't thank ya enough for the quick turn around on fixing this!
[FFXVIFix.log](https://github.com/user-attachments/files/17101179/FFXVIFix.log)

**Comment by Jipper88** [comment] 2024-09-23 18:54
Just tried the 0.8.2 test and can confirm its also fixed the issue for me. no more black bars in map and icons no longer moving from cursor,

Good work (y) mod is spot on and making this game playable on ultrawides.

**Comment by Lyall** [comment] 2024-09-24 00:20
Thanks for testing both of you. I've added this to the latest version (v0.8.2) and will close this issue.

**Closed by Lyall** 2024-09-24 00:20 UTC
