### ISSUE TITLE
FMVs are still 16:9 and usually weird colors or images

### ISSUE THREAD

**Issue by nlikeflynn** [Lyall/FFXVIFix#48] opened 2024-09-19 20:16 UTC
Title. Plus, I noticed that in some cutscenes, words are still displayed over the pillars where 21:9 content would be. Sorry I couldn’t grab a screen image in time.

**Comment by Lyall** [comment] 2024-09-19 20:27
This a dupe of #7. As for the words displaying over the pillarboxing, are you running the HUD size at 16:9? If not, then things like that will happen, hence why 16:9 is the default.

**Comment by WaffleWasher** [comment] 2024-09-19 20:29
0 if you have a 3440x1440 res, which is 43:18 ratio, a bit wider than 21:9

**Comment by nlikeflynn** [comment] 2024-09-19 20:45
I will try the suggestions here. Thank you. Closing.

**Closed** 2024-09-19 20:45 UTC
